### ISSUE TITLE
tp仓库怎么无了

### ISSUE THREAD

**Issue by LovesAsuna** [xiyan520/img#1]
我还引用了这仓库的很多图片，突然就没了:(

**Comment by xiyan520** [comment]
很抱歉我并不知道我的tp仓库还有人使用，目前已经恢复了，如果还有人再用，我会考虑后续更新图源，给你带来不便抱歉

**Comment by LovesAsuna** [comment]
好耶好起来了

**Comment by xiyan520** [comment]
后续更新图源，原图源可能会有替换，毕竟实在太久了，因为这个tp库是我以前搞api建立起来了，目前api已经更新到第三版，tp图库的资源可能会全面调整，当然风景图不在调整范围之类ʕ ᵔᴥᵔ ʔ
